export const BACKEND_HOST: string = 'http://localhost:5000';
//export const BACKEND_HOST: string = 'https://market-place-v1o0.onrender.com';
export const API: string = `${BACKEND_HOST}/api`;
export const API_AUTH: string = `${API}/auth`;
export const API_PRODUCTS: string = `${API}/products`;
export const API_COMPILATIONS: string = `${API}/compilations`;
export const API_CART: string = `${API}/cart`;
export const API_COMPANIES: string = `${API}/companies`;
export const API_BRANDS: string = `${API}/brands`;

export const ROUTE_HOME = '/';
export const ROUTE_LOGIN = '/login';
export const ROUTE_CART = '/cart';
export const ROUTE_ORDER = '/order';
export const ROUTE_PRODUCT = '/product';
export const ROUTE_PRODUCT_ID = '/product/:id';
export const ROUTE_PROFILE = '/profile';
export const ROUTE_CATALOGUE = '/catalogue';
export const ROUTE_BUSINESS = '/business';