export const DATABASE = 'DATABASE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TOKENS_REPOSITORY = 'TOKENS_REPOSITORY';
export const PRODUCTS_REPOSITORY = 'PRODUCTS_REPOSITORY';
export const ORDERS_REPOSITORY = 'ORDERS_REPOSITORY';